package postgres

import (
	"context"
	"database/sql"
	"maps"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/blang/semver"
	"github.com/coroot/coroot-cluster-agent/common"
	"github.com/coroot/coroot-cluster-agent/metrics/dbtracker"
	"github.com/coroot/logger"
	_ "github.com/lib/pq"
	"github.com/prometheus/client_golang/prometheus"
)

const (
	topQueriesN               = 20
	hardQuerySizeLimit        = 4096
	topLongTransactions       = 20
	minLongTransactionSeconds = 10
)

var (
	dUp          = desc("pg_up", "Is the server reachable")
	dProbe       = desc("pg_probe_seconds", "Empty query execution time")
	dScrapeError = desc("pg_scrape_error", "Scrape error", "error", "warning")

	dInfo     = desc("pg_info", "Server info", "server_version")
	dSettings = desc("pg_setting", "Value of the pg_setting variable", "name", "unit")

	dConnections = desc("pg_connections", "Number of database connections", "db", "user", "state", "wait_event_type", "query")

	dAutovacuumWorkers = desc("pg_autovacuum_workers", "Number of running autovacuum worker processes")

	dLatency = desc("pg_latency_seconds", "Query execution time", "summary")

	dDbQueries = desc("pg_db_queries_per_second", "Number of queries executed in the database per second", "db")

	dTopQueryCalls  = desc("pg_top_query_calls_per_second", "Number of times the query was executed", "db", "user", "query")
	dTopQueryTime   = desc("pg_top_query_time_per_second", "Time spent executing the query", "db", "user", "query")
	dTopQueryIOTime = desc("pg_top_query_io_time_per_second", "Time the query spent awaiting IO", "db", "user", "query")

	// additional pg_stat_statements counters of the top queries, indexed by ssRows...ssWalBytes
	dTopQueryCounters = [ssCountersN]*prometheus.Desc{
		ssRows:              desc("pg_top_query_rows_per_second", "Number of rows retrieved or affected by the query", "db", "user", "query"),
		ssSharedBlksHit:     desc("pg_top_query_shared_blks_hit_per_second", "Number of shared block cache hits by the query", "db", "user", "query"),
		ssSharedBlksRead:    desc("pg_top_query_shared_blks_read_per_second", "Number of shared blocks read by the query", "db", "user", "query"),
		ssSharedBlksDirtied: desc("pg_top_query_shared_blks_dirtied_per_second", "Number of shared blocks dirtied by the query", "db", "user", "query"),
		ssSharedBlksWritten: desc("pg_top_query_shared_blks_written_per_second", "Number of shared blocks written by the query", "db", "user", "query"),
		ssLocalBlksHit:      desc("pg_top_query_local_blks_hit_per_second", "Number of local block cache hits by the query", "db", "user", "query"),
		ssLocalBlksRead:     desc("pg_top_query_local_blks_read_per_second", "Number of local blocks read by the query", "db", "user", "query"),
		ssLocalBlksDirtied:  desc("pg_top_query_local_blks_dirtied_per_second", "Number of local blocks dirtied by the query", "db", "user", "query"),
		ssLocalBlksWritten:  desc("pg_top_query_local_blks_written_per_second", "Number of local blocks written by the query", "db", "user", "query"),
		ssTempBlksRead:      desc("pg_top_query_temp_blks_read_per_second", "Number of temp blocks read by the query", "db", "user", "query"),
		ssTempBlksWritten:   desc("pg_top_query_temp_blks_written_per_second", "Number of temp blocks written by the query", "db", "user", "query"),
		ssPlanTime:          desc("pg_top_query_plan_time_per_second", "Time spent planning the query (PG13+, requires pg_stat_statements.track_planning)", "db", "user", "query"),
		ssWalBytes:          desc("pg_top_query_wal_bytes_per_second", "Amount of WAL generated by the query (PG13+)", "db", "user", "query"),
	}
	dTopQueryExecTimeMean = desc("pg_top_query_exec_time_mean_seconds", "Mean execution time of the query since the last pg_stat_statements reset", "db", "user", "query")
	dTopQueryExecTimeMin  = desc("pg_top_query_exec_time_min_seconds", "Minimum execution time of the query since the last pg_stat_statements reset", "db", "user", "query")
	dTopQueryExecTimeMax  = desc("pg_top_query_exec_time_max_seconds", "Maximum execution time of the query since the last pg_stat_statements reset", "db", "user", "query")

	dWaitEventSessions = desc("pg_wait_event_sessions", "Number of non-idle backends waiting on the wait event at the time of the snapshot", "wait_event_type", "wait_event")

	dIndexUnused        = desc("pg_index_unused_bytes", "Size of a never-scanned (idx_scan = 0 since the stats reset) non-unique index; top indexes by size", "db", "schema", "table", "index")
	dDbUnusedIndexes    = desc("pg_db_unused_indexes", "Number of never-scanned non-unique indexes in the database", "db")
	dDbUnusedIndexBytes = desc("pg_db_unused_indexes_bytes", "Total size of never-scanned non-unique indexes in the database", "db")
	dDbDuplicateIndexes = desc("pg_db_duplicate_indexes", "Number of redundant indexes in the database (same table, columns, expressions, predicate, operator classes and access method as another index)", "db")

	dLockAwaitingQueries = desc("pg_lock_awaiting_queries", "Number of queries awaiting a lock", "db", "user", "blocking_query")

	dWalReceiverStatus = desc("pg_wal_receiver_status", "WAL receiver status: 1 if the receiver is connected, otherwise 0", "sender_host", "sender_port")
	dWalReplayPaused   = desc("pg_wal_replay_paused", "Whether WAL replay paused or not")
	dWalCurrentLsn     = desc("pg_wal_current_lsn", "Current WAL sequence number")
	dWalReceiveLsn     = desc("pg_wal_receive_lsn", "WAL sequence number that has been received and synced to disk by streaming replication")
	dWalReplyLsn       = desc("pg_wal_reply_lsn", "WAL sequence number that has been replayed during recovery")

	dCheckpointsScheduled    = desc("pg_checkpoints_scheduled_total", "Number of scheduled checkpoints, including skipped ones", "type")
	dCheckpoints             = desc("pg_checkpoints_total", "Number of checkpoints that have been completed")
	dRestartpoints           = desc("pg_restartpoints_total", "Number of restartpoints that have been completed on a standby")
	dBuffersWritten          = desc("pg_buffers_written_total", "Total number of dirty buffers flushed to disk", "source")
	dTimeSinceLastCheckpoint = desc("pg_time_since_last_checkpoint_seconds", "Seconds since the last checkpoint observed by the agent")
	dWalSinceLastCheckpoint  = desc("pg_wal_since_last_checkpoint_bytes", "Amount of WAL written since the last completed checkpoint (to be replayed in the case of a crash)")
	dWalSize                 = desc("pg_wal_size_bytes", "Size of the WAL directory")
	dReplicationSlotRetained = desc("pg_replication_slot_retained_wal_bytes", "Amount of WAL retained for the replication slot", "slot", "active", "wal_status")
	dXidAge                  = desc("pg_xid_age", "Transactions since the oldest unfrozen transaction ID (age of datfrozenxid)", "db")
	dMultixactAge            = desc("pg_multixact_age", "Multixacts since the oldest unfrozen multixact ID (age of datminmxid)", "db")
	dOldestXminAge           = desc("pg_oldest_xmin_age", "Age, in transactions, of the oldest transaction ID held back from freezing, by holder", "holder")
	dTransactionSeconds      = desc("pg_transaction_seconds", "Age of the longest-running transaction, by query", "db", "user", "query")
	dWalArchivedSegments     = desc("pg_wal_archived_segments_total", "Number of WAL files successfully archived")
	dWalArchiveFailures      = desc("pg_wal_archive_failures_total", "Number of failed attempts to archive WAL files")
	dWalArchivingStatus      = desc("pg_wal_archiving_status", "1 if the last WAL archive attempt succeeded, 0 if it failed")

	dDbSize          = desc("pg_database_size_bytes", "Total size of the database in bytes", "db")
	dTableSize       = desc("pg_table_size_bytes", "Total size of the table in bytes including indexes and TOAST", "db", "schema", "table")
	dTableSizeGrowth = desc("pg_table_size_growth_bytes_per_second", "Table size growth rate in bytes per second", "db", "schema", "table")

	dDbTableBloat = desc("pg_db_table_bloat_bytes", "Estimated wasted space across all tables of the database", "db")
	dDbIndexBloat = desc("pg_db_index_bloat_bytes", "Estimated wasted space across all indexes of the database", "db")
	dTableBloat   = desc("pg_table_bloat_bytes", "Estimated wasted space in the table heap", "db", "schema", "table")
	dIndexBloat   = desc("pg_index_bloat_bytes", "Estimated wasted space in the index", "db", "schema", "table", "index")

	dTableDeadTupleBytes = desc("pg_table_dead_tuple_bytes", "Estimated size of dead tuples not yet reclaimed by vacuum", "db", "schema", "table")
	dTableDeadTuples     = desc("pg_table_dead_tuples", "Number of dead tuples not yet reclaimed by vacuum", "db", "schema", "table")
	dTableLiveTuples     = desc("pg_table_live_tuples", "Estimated number of live tuples", "db", "schema", "table")

	dTableSecondsSinceAutovacuum = desc("pg_table_seconds_since_last_autovacuum", "Seconds since the last autovacuum of the table", "db", "schema", "table")
	dTableVacuumInProgress       = desc("pg_table_vacuum_in_progress", "1 if a vacuum is currently running on the table; not reported otherwise", "db", "schema", "table")
	dTableVacuumThrottled        = desc("pg_table_vacuum_throttled", "1 if the running vacuum is sleeping on the cost-based delay (VacuumDelay) at scrape time, 0 otherwise; reported only while a vacuum is in progress", "db", "schema", "table")

	dTableModsSinceAnalyze    = desc("pg_table_mods_since_analyze", "Rows modified (inserted/updated/deleted) since the table's statistics were last analyzed", "db", "schema", "table")
	dTableReltuples           = desc("pg_table_reltuples", "Planner's estimate of the number of live rows in the table (pg_class.reltuples)", "db", "schema", "table")
	dTableSecondsSinceAnalyze = desc("pg_table_seconds_since_last_analyze", "Seconds since the table's planner statistics were last refreshed (ANALYZE or autoanalyze)", "db", "schema", "table")
	dTableSetting             = desc("pg_table_setting", "Per-table autovacuum/autoanalyze reloption overrides carried as labels (empty = not overridden); reported only for monitored tables that override a setting", "db", "schema", "table", "autovacuum_disabled", "autovacuum_vacuum_scale_factor", "autovacuum_vacuum_threshold", "autovacuum_vacuum_cost_delay", "autovacuum_vacuum_cost_limit", "autovacuum_analyze_scale_factor", "autovacuum_analyze_threshold")
)

type QueryKey struct {
	Query string
	DB    string
	User  string
}

func (k QueryKey) EqualByQueryPrefix(other QueryKey) bool {
	if k.User != other.User || k.DB != other.DB {
		return false
	}
	if strings.HasPrefix(k.Query, other.Query) {
		return true
	}
	return false
}

type ConnectionKey struct {
	QueryKey
	State         string
	WaitEventType string
}

// pgState is the result of a snapshot. Once published via Collector.state it is never
// modified, so Collect can read it without holding the lock.
type pgState struct {
	origVersion string

	ssCurr            *ssSnapshot
	ssPrev            *ssSnapshot
	saCurr            *saSnapshot
	saPrev            *saSnapshot
	settings          []Setting
	replicationStatus *replicationStatus

	cpTimed          float64
	cpRequested      float64
	cpDone           float64
	cpRestartsDone   float64
	cpBuffers        float64
	cpWalBytes       sql.Null[float64]
	lastCheckpointAt time.Time

	walSize          sql.Null[float64]
	replicationSlots []replicationSlot
	archStats        *archiverStats
	archArchived     float64
	archFailed       float64
	wraparound       *wraparoundStats
	statViews        []*statResult

	scrapeErrors map[string]bool // error reason -> true
}

type Collector struct {
	ctx           context.Context
	ctxCancelFunc context.CancelFunc
	wg            sync.WaitGroup

	scrapeInterval time.Duration
	collectTimeout time.Duration

	db *sql.DB

	// accessed only by the snapshot goroutine
	cpPrev           *checkpointStats
	archPrev         *archiverStats
	prevSettingsText string

	dbTracker        *databaseTracker
	excludeDatabases map[string]bool
	emitter          dbtracker.ChangeEmitter
	targetAddr       string

	lock   sync.RWMutex // guards state
	state  *pgState
	logger logger.Logger
}

func New(dsn string, scrapeInterval, collectTimeout time.Duration, logger logger.Logger, emitter dbtracker.ChangeEmitter, targetAddr string, maxTablesPerDB int, trackSizes, trackBloat bool, excludeDatabases []string) (*Collector, error) {
	ctx, cancelFunc := context.WithCancel(context.Background())
	c := &Collector{
		ctx:              ctx,
		logger:           logger,
		ctxCancelFunc:    cancelFunc,
		state:            &pgState{},
		scrapeInterval:   scrapeInterval,
		collectTimeout:   collectTimeout,
		targetAddr:       targetAddr,
		emitter:          emitter,
		excludeDatabases: map[string]bool{},
	}
	for _, dbName := range excludeDatabases {
		c.excludeDatabases[dbName] = true
	}
	var err error
	c.db, err = sql.Open("postgres", dsn)
	if err != nil {
		return nil, err
	}
	c.db.SetMaxOpenConns(1)
	trackSchema := c.emitter != nil
	if trackSchema || trackSizes || trackBloat {
		// the tracker runs concurrently with the snapshot: give it its own connection
		// so that neither of them waits for the other one
		c.db.SetMaxOpenConns(2)
		c.dbTracker = newDatabaseTracker(c.db, dsn, maxTablesPerDB, trackSchema, trackSizes, trackBloat, excludeDatabases, snapshotTimeout(scrapeInterval), logger)
	}
	pingCtx, pingCancelFunc := context.WithTimeout(ctx, collectTimeout)
	defer pingCancelFunc()
	if err := c.db.PingContext(pingCtx); err != nil {
		c.logger.Warning("probe failed:", err)
	}
	c.wg.Add(1)
	go func() {
		defer c.wg.Done()
		ticker := time.NewTicker(scrapeInterval)
		defer ticker.Stop()
		c.snapshot()
		for {
			select {
			case <-ticker.C:
				c.snapshot()
			case <-ctx.Done():
				c.logger.Info("stopping pg collector")
				return
			}
		}
	}()
	if c.dbTracker != nil {
		c.wg.Add(1)
		go func() {
			defer c.wg.Done()
			// each database gets its own deadline inside collectSnapshot,
			// so there is no overall deadline for a tracking run
			c.dbTracker.Run(ctx, 0, c.emitter, c.targetAddr)
		}()
	}
	return c, nil
}

func snapshotTimeout(scrapeInterval time.Duration) time.Duration {
	timeout := scrapeInterval - time.Second
	if timeout <= 0 {
		timeout = time.Second
	}
	return timeout
}

func (c *Collector) getState() *pgState {
	c.lock.RLock()
	defer c.lock.RUnlock()
	return c.state
}

func (c *Collector) addScrapeError(st *pgState, err error) {
	c.logger.Warning(err)
	st.scrapeErrors[errorReason(err)] = true
}

// snapshot queries the server without holding the lock: the new state is built from a
// copy of the current one and published at the end, so a slow server never blocks Collect.
func (c *Collector) snapshot() {
	ctx, cancelFunc := context.WithTimeout(c.ctx, snapshotTimeout(c.scrapeInterval))
	defer cancelFunc()

	st := *c.getState() // shallow copy: fields are replaced, never mutated in place
	st.scrapeErrors = map[string]bool{}
	defer func() {
		c.lock.Lock()
		c.state = &st
		c.lock.Unlock()
	}()

	st.origVersion = ""
	var version semver.Version
	var rawVersion string
	err := c.db.QueryRowContext(ctx, `SELECT setting FROM pg_settings WHERE name='server_version'`).Scan(&rawVersion)
	if err != nil {
		c.addScrapeError(&st, err)
		return
	}
	st.origVersion, version, err = parsePgVersion(rawVersion)
	if err != nil {
		c.addScrapeError(&st, err)
		return
	}

	if st.settings, err = c.getSettings(ctx); err != nil {
		c.addScrapeError(&st, err)
	}

	if st.replicationStatus, err = c.getReplicationStatus(ctx, version); err != nil {
		c.addScrapeError(&st, err)
	}

	if err = c.getCheckpointStats(ctx, version, &st); err != nil {
		c.addScrapeError(&st, err)
	}

	if err = c.getWalStats(ctx, version, &st); err != nil {
		c.addScrapeError(&st, err)
	}

	if err = c.getWraparoundStats(ctx, version, &st); err != nil {
		c.addScrapeError(&st, err)
	}

	c.getStatViews(ctx, version.Major, &st)

	querySizeLimit := 0
	for _, s := range st.settings {
		if s.Name == "track_activity_query_size" {
			switch s.Unit {
			case "B":
				querySizeLimit = int(s.Value)
			case "kB":
				querySizeLimit = int(s.Value) * 1024
			default:
				querySizeLimit = int(s.Value)
			}
			break
		}
	}
	if querySizeLimit == 0 || querySizeLimit > hardQuerySizeLimit {
		querySizeLimit = hardQuerySizeLimit
	}

	st.ssPrev = st.ssCurr
	st.saPrev = st.saCurr
	prevStatements := map[statementId]ssRow{}
	if st.ssPrev != nil {
		prevStatements = st.ssPrev.rows
	}
	st.ssCurr, err = c.getStatStatements(ctx, version, querySizeLimit, prevStatements)
	if err != nil {
		// pg_stat_statements is optional: keep collecting pg_stat_activity
		c.addScrapeError(&st, err)
		st.ssCurr = nil
	}
	st.saCurr, err = c.getPgStatActivity(ctx, version, querySizeLimit)
	if err != nil {
		c.addScrapeError(&st, err)
		return
	}

	if c.emitter != nil {
		c.trackSettingsChanges(st.settings)
	}
}

func (c *pgState) summaries() (map[QueryKey]*QuerySummary, time.Duration) {
	if c.saCurr == nil || c.saPrev == nil || c.ssCurr == nil || c.ssPrev == nil {
		return nil, 0
	}
	res := map[QueryKey]*QuerySummary{}
	getOrCreateSummary := func(k QueryKey, searchByPrefix bool) *QuerySummary {
		s := res[k]
		if s == nil && searchByPrefix {
			for qk, ss := range res {
				if qk.EqualByQueryPrefix(k) {
					s = ss
					break
				}
			}
		}
		if s == nil {
			s = &QuerySummary{}
			res[k] = s
		}
		return s
	}

	for id, r := range c.ssCurr.rows {
		getOrCreateSummary(r.QueryKey(id), false).updateFromStatStatements(r, c.ssPrev.rows[id])
	}
	for _, conn := range c.saCurr.connections {
		getOrCreateSummary(conn.QueryKey(), true).updateFromStatActivity(c.saPrev.ts, c.saCurr.ts, conn)
	}
	for pid, prev := range c.saPrev.connections {
		if !prev.IsClientBackend() || prev.State.String != "active" {
			continue
		}
		curr, ok := c.saCurr.connections[pid]
		if ok && curr.State.String == "active" && curr.QueryStart.Time.Equal(prev.QueryStart.Time) { // still executing
			continue
		}
		// prev query finished
		getOrCreateSummary(prev.QueryKey(), true).correctFromPrevStatActivity(c.saPrev.ts, prev)
	}
	return res, c.ssCurr.ts.Sub(c.ssPrev.ts)
}

func (c *pgState) connectionMetrics(ch chan<- prometheus.Metric) {
	if c.saCurr == nil {
		return
	}
	byPid := map[int]QueryKey{}
	awaitingQueriesByBlockingPid := map[int]float64{}
	connectionsByKey := map[ConnectionKey]float64{}

	for pid, conn := range c.saCurr.connections {
		queryKey := conn.QueryKey()
		byPid[pid] = queryKey
		if conn.BlockingPid.Int32 > 0 {
			awaitingQueriesByBlockingPid[int(conn.BlockingPid.Int32)]++
		}
		key := ConnectionKey{
			QueryKey:      queryKey,
			State:         conn.State.String,
			WaitEventType: conn.WaitEventType.String,
		}
		connectionsByKey[key]++
	}

	for k, count := range connectionsByKey {
		ch <- gauge(dConnections, count, k.DB, k.User, k.State, k.WaitEventType, k.Query)
	}
	for k, count := range c.saCurr.waitEvents {
		ch <- gauge(dWaitEventSessions, count, k.eventType, k.event)
	}
	ch <- gauge(dAutovacuumWorkers, c.saCurr.autovacuumWorkers)

	xactSecondsByQuery := map[QueryKey]float64{}
	for _, conn := range c.saCurr.connections {
		if !conn.IsClientBackend() || !conn.XactSeconds.Valid || conn.XactSeconds.Float64 < minLongTransactionSeconds {
			continue
		}
		k := conn.QueryKey()
		if k.Query == "" {
			k.Query = "~empty"
		}
		if age := conn.XactSeconds.Float64; age > xactSecondsByQuery[k] {
			xactSecondsByQuery[k] = age
		}
	}
	for k, age := range common.TopNMapByValue(xactSecondsByQuery, topLongTransactions) {
		ch <- gauge(dTransactionSeconds, age, k.DB, k.User, k.Query)
	}

	awaitingQueriesByBlockingQuery := map[QueryKey]float64{}
	for blockingPid, awaitingQueries := range awaitingQueriesByBlockingPid {
		blockingQuery, ok := byPid[blockingPid]
		if !ok {
			continue
		}
		awaitingQueriesByBlockingQuery[blockingQuery] += awaitingQueries
	}
	for blockingQuery, awaitingQueries := range awaitingQueriesByBlockingQuery {
		ch <- gauge(dLockAwaitingQueries, awaitingQueries, blockingQuery.DB, blockingQuery.User, blockingQuery.Query)
	}
}

func (c *Collector) queryMetrics(ch chan<- prometheus.Metric, st *pgState) {
	summaries, interval := st.summaries()
	if summaries == nil {
		c.logger.Warning("no summaries")
		return
	}

	latency := NewLatencySummary()
	queriesByDB := map[string]float64{}
	for k, summary := range summaries {
		latency.Add(summary.TotalTime, uint64(summary.Queries))
		queriesByDB[k.DB] += summary.Queries
	}
	for s, v := range latency.GetSummaries(50, 75, 95, 99) {
		ch <- gauge(dLatency, v, s)
	}

	for db, queries := range queriesByDB {
		ch <- gauge(dDbQueries, queries/interval.Seconds(), db)
	}

	for k, summary := range common.TopNMap(summaries, topQueriesN, func(s *QuerySummary) float64 { return s.TotalTime }) {
		ch <- gauge(dTopQueryCalls, summary.Queries/interval.Seconds(), k.DB, k.User, k.Query)
		ch <- gauge(dTopQueryTime, summary.TotalTime/interval.Seconds(), k.DB, k.User, k.Query)
		ch <- gauge(dTopQueryIOTime, summary.IOTime/interval.Seconds(), k.DB, k.User, k.Query)
		summary.extraMetrics(ch, interval, k)
	}
}

// extraMetrics emits the additional pg_stat_statements series of a top query.
func (s *QuerySummary) extraMetrics(ch chan<- prometheus.Metric, interval time.Duration, k QueryKey) {
	if interval <= 0 {
		return
	}
	for i, d := range dTopQueryCounters {
		if !s.hasCounter[i] {
			continue
		}
		v := s.Counters[i] / interval.Seconds()
		if i == ssPlanTime {
			v /= 1000 // ms -> s
		}
		ch <- gauge(d, v, k.DB, k.User, k.Query)
	}
	if mean, ok := s.ExecTimeMean(); ok {
		ch <- gauge(dTopQueryExecTimeMean, mean/1000, k.DB, k.User, k.Query)
	}
	if s.execMin.Valid {
		ch <- gauge(dTopQueryExecTimeMin, s.execMin.Float64/1000, k.DB, k.User, k.Query)
	}
	if s.execMax.Valid {
		ch <- gauge(dTopQueryExecTimeMax, s.execMax.Float64/1000, k.DB, k.User, k.Query)
	}
}

func (c *Collector) tableSizeMetrics(ch chan<- prometheus.Metric) {
	if c.dbTracker == nil {
		return
	}
	if c.dbTracker.trackSizes {
		dbSizes, tableGrowth := c.dbTracker.Sizes()
		for dbName, snap := range dbSizes {
			ch <- gauge(dDbSize, snap.DatabaseSize, dbName)
			for _, t := range snap.Tables {
				ch <- gauge(dTableSize, t.Size, dbName, t.Schema, t.Table)
			}
		}
		for _, g := range tableGrowth {
			ch <- gauge(dTableSizeGrowth, g.Growth, g.DB, g.Schema, g.Table)
		}
	}
	for dbName, s := range c.dbTracker.indexResults() {
		if s.unused.Valid {
			ch <- gauge(dDbUnusedIndexes, s.unused.V.count, dbName)
			ch <- gauge(dDbUnusedIndexBytes, s.unused.V.bytes, dbName)
			for _, ix := range s.unused.V.top {
				ch <- gauge(dIndexUnused, ix.Bytes, dbName, ix.Schema, ix.Table, ix.Index)
			}
		}
		if s.duplicates.Valid {
			ch <- gauge(dDbDuplicateIndexes, s.duplicates.V, dbName)
		}
	}
	bloat, tableStats, vacuumProgress := c.dbTracker.results()
	for dbName, b := range bloat {
		ch <- gauge(dDbTableBloat, b.TableTotal, dbName)
		ch <- gauge(dDbIndexBloat, b.IndexTotal, dbName)
		for _, t := range b.TopTables {
			ch <- gauge(dTableBloat, t.Bytes, dbName, t.Schema, t.Table)
		}
		for _, ix := range b.TopIndexes {
			ch <- gauge(dIndexBloat, ix.Bytes, dbName, ix.Schema, ix.Table, ix.Index)
		}
	}
	for dbName, entries := range tableStats {
		for _, e := range entries {
			ch <- gauge(dTableReltuples, e.Reltuples, dbName, e.Schema, e.Table)
			if e.DeadBytes > 0 {
				ch <- gauge(dTableDeadTupleBytes, e.DeadBytes, dbName, e.Schema, e.Table)
				ch <- gauge(dTableDeadTuples, e.DeadTuples, dbName, e.Schema, e.Table)
				ch <- gauge(dTableLiveTuples, e.LiveTuples, dbName, e.Schema, e.Table)
			}
			if e.AutovacuumAge.Valid {
				ch <- gauge(dTableSecondsSinceAutovacuum, e.AutovacuumAge.Float64, dbName, e.Schema, e.Table)
			}
			if e.ModsSinceAnalyze > 0 {
				ch <- gauge(dTableModsSinceAnalyze, e.ModsSinceAnalyze, dbName, e.Schema, e.Table)
			}
			if e.AnalyzeAge.Valid {
				ch <- gauge(dTableSecondsSinceAnalyze, e.AnalyzeAge.Float64, dbName, e.Schema, e.Table)
			}
			if e.Reloptions.Valid && e.Reloptions.String != "" {
				if s := parseTableSettings(e.Reloptions.String); len(s) > 0 {
					ch <- gauge(dTableSetting, 1, dbName, e.Schema, e.Table,
						s["autovacuum_disabled"], s["autovacuum_vacuum_scale_factor"], s["autovacuum_vacuum_threshold"],
						s["autovacuum_vacuum_cost_delay"], s["autovacuum_vacuum_cost_limit"],
						s["autovacuum_analyze_scale_factor"], s["autovacuum_analyze_threshold"])
				}
			}
		}
	}
	for dbName, entries := range vacuumProgress {
		for _, v := range entries {
			ch <- gauge(dTableVacuumInProgress, 1, dbName, v.Schema, v.Table)
			throttled := 0.0
			if v.Throttled {
				throttled = 1
			}
			ch <- gauge(dTableVacuumThrottled, throttled, dbName, v.Schema, v.Table)
		}
	}
}

func (c *Collector) Close() error {
	c.ctxCancelFunc()
	c.wg.Wait()
	return c.db.Close()
}

func (c *Collector) Collect(ch chan<- prometheus.Metric) {
	ctx, cancelFunc := context.WithTimeout(c.ctx, c.collectTimeout)
	defer cancelFunc()
	now := time.Now()
	if err := c.db.PingContext(ctx); err != nil {
		c.logger.Warning("probe failed:", err)
		ch <- gauge(dUp, 0)
		ch <- gauge(dScrapeError, 1, errorReason(err), "")
		return
	}
	ch <- gauge(dUp, 1)
	ch <- gauge(dProbe, time.Since(now).Seconds())

	st := c.getState()
	if st.origVersion != "" {
		ch <- gauge(dInfo, 1, st.origVersion)
	}

	warnings := st.scrapeErrors
	if c.dbTracker != nil {
		if trackerErrors := c.dbTracker.errorReasons(); len(trackerErrors) > 0 {
			warnings = maps.Clone(warnings)
			if warnings == nil {
				warnings = map[string]bool{}
			}
			maps.Copy(warnings, trackerErrors)
		}
	}
	if len(warnings) > 0 {
		for e := range warnings {
			ch <- gauge(dScrapeError, 1, "", e)
		}
	} else {
		ch <- gauge(dScrapeError, 0, "", "")
	}

	st.connectionMetrics(ch)
	for _, r := range st.statViews {
		r.emit(ch)
	}
	c.queryMetrics(ch, st)
	c.tableSizeMetrics(ch)
	for _, s := range st.settings {
		if s.IsMetric {
			ch <- gauge(dSettings, s.Value, s.Name, s.Unit)
		}
	}

	if st.replicationStatus != nil {
		rs := st.replicationStatus
		if rs.isInRecovery {
			if rs.receiveLsn.Valid {
				ch <- counter(dWalReceiveLsn, float64(rs.receiveLsn.Int64))
			}
			if rs.replyLsn.Valid {
				ch <- counter(dWalReplyLsn, float64(rs.replyLsn.Int64))
			}
			isReplayPaused := 0.0
			if rs.isReplayPaused {
				isReplayPaused = 1.0
			}
			ch <- gauge(dWalReplayPaused, isReplayPaused)
			host, port, err := rs.primaryHostPort()
			if err != nil {
				c.logger.Warning(err)
			}
			ch <- gauge(dWalReceiverStatus, float64(rs.walReceiverStatus), host, port)
		} else {
			if rs.currentLsn.Valid {
				ch <- counter(dWalCurrentLsn, float64(rs.currentLsn.Int64))
			}
		}
	}

	ch <- counter(dCheckpointsScheduled, st.cpTimed, "timed")
	ch <- counter(dCheckpointsScheduled, st.cpRequested, "requested")
	ch <- counter(dCheckpoints, st.cpDone)
	ch <- counter(dRestartpoints, st.cpRestartsDone)
	ch <- counter(dBuffersWritten, st.cpBuffers, "checkpointer")
	if st.cpWalBytes.Valid {
		ch <- gauge(dWalSinceLastCheckpoint, st.cpWalBytes.V)
	}
	if st.walSize.Valid {
		ch <- gauge(dWalSize, st.walSize.V)
	}
	for _, s := range st.replicationSlots {
		if s.retained.Valid {
			ch <- gauge(dReplicationSlotRetained, s.retained.V, s.name, strconv.FormatBool(s.active), s.walStatus)
		}
	}
	ch <- counter(dWalArchivedSegments, st.archArchived)
	ch <- counter(dWalArchiveFailures, st.archFailed)
	if w := st.wraparound; w != nil {
		for db, v := range w.xidAge {
			ch <- gauge(dXidAge, v, db)
		}
		for db, v := range w.multixactAge {
			ch <- gauge(dMultixactAge, v, db)
		}
		for holder, v := range w.xminAgeByHolder {
			ch <- gauge(dOldestXminAge, v, holder)
		}
	}
	if a := st.archStats; a != nil {
		if a.lastArchived.Valid || a.lastFailed.Valid {
			failing := a.lastFailed.Valid && (!a.lastArchived.Valid || a.lastFailed.V.After(a.lastArchived.V))
			status := 1.0
			if failing {
				status = 0.0
			}
			ch <- gauge(dWalArchivingStatus, status)
		}
	}
	if !st.lastCheckpointAt.IsZero() {
		ch <- gauge(dTimeSinceLastCheckpoint, time.Since(st.lastCheckpointAt).Seconds())
	}
}

func (c *Collector) Describe(ch chan<- *prometheus.Desc) {
	ch <- dUp
	ch <- dProbe
	ch <- dScrapeError
	ch <- dInfo
	ch <- dConnections
	ch <- dAutovacuumWorkers
	ch <- dTableVacuumInProgress
	ch <- dTableVacuumThrottled
	ch <- dLatency
	ch <- dLockAwaitingQueries
	ch <- dSettings
	ch <- dTopQueryCalls
	ch <- dTopQueryTime
	ch <- dTopQueryIOTime
	for _, d := range dTopQueryCounters {
		ch <- d
	}
	ch <- dTopQueryExecTimeMean
	ch <- dTopQueryExecTimeMin
	ch <- dTopQueryExecTimeMax
	ch <- dWaitEventSessions
	ch <- dIndexUnused
	ch <- dDbUnusedIndexes
	ch <- dDbUnusedIndexBytes
	ch <- dDbDuplicateIndexes
	for _, d := range statViewDescs() {
		ch <- d
	}
	ch <- dDbQueries
	ch <- dWalReceiverStatus
	ch <- dWalReplayPaused
	ch <- dWalCurrentLsn
	ch <- dWalReceiveLsn
	ch <- dWalReplyLsn
	ch <- dCheckpointsScheduled
	ch <- dCheckpoints
	ch <- dRestartpoints
	ch <- dBuffersWritten
	ch <- dTimeSinceLastCheckpoint
	ch <- dWalSinceLastCheckpoint
	ch <- dWalSize
	ch <- dReplicationSlotRetained
	ch <- dWalArchivedSegments
	ch <- dWalArchiveFailures
	ch <- dXidAge
	ch <- dMultixactAge
	ch <- dOldestXminAge
	ch <- dTransactionSeconds
	ch <- dWalArchivingStatus
	ch <- dDbSize
	ch <- dTableSize
	ch <- dTableSizeGrowth
	ch <- dDbTableBloat
	ch <- dDbIndexBloat
	ch <- dTableBloat
	ch <- dIndexBloat
	ch <- dTableDeadTupleBytes
	ch <- dTableDeadTuples
	ch <- dTableLiveTuples
	ch <- dTableSecondsSinceAutovacuum
	ch <- dTableModsSinceAnalyze
	ch <- dTableReltuples
	ch <- dTableSecondsSinceAnalyze
	ch <- dTableSetting
}

func desc(name, help string, labels ...string) *prometheus.Desc {
	return prometheus.NewDesc(name, help, labels, nil)
}

func gauge(desc *prometheus.Desc, value float64, labels ...string) prometheus.Metric {
	return prometheus.MustNewConstMetric(desc, prometheus.GaugeValue, value, labels...)
}

func counter(desc *prometheus.Desc, value float64, labels ...string) prometheus.Metric {
	return prometheus.MustNewConstMetric(desc, prometheus.CounterValue, value, labels...)
}
